kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  labels:
    app: {{ include "helm1.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  nginx.conf: |-
    events {
    }
    http {
      server {
        #listen 80 default_server;
        #listen [::]:80 default_server;
        listen 0.0.0.0:{{ .Values.phpService.internalPort }};

        # Set nginx to serve files from the shared volume!
        root /app;
        server_name _;
        location / {
          index /index.php
          try_files $uri $uri/ =404;
        }
        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    -- phpMyAdmin SQL Dump
    -- version 5.1.1
    -- https://www.phpmyadmin.net/
    --
    -- Host: 127.0.0.1
    -- Generation Time: Mar 30, 2022 at 03:20 PM
    -- Server version: 10.4.22-MariaDB
    -- PHP Version: 7.4.27
 
    CREATE DATABASE emp_demo_database;
    USE emp_demo_database;

    SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
    START TRANSACTION;
    SET time_zone = "+00:00";
    
    
    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!40101 SET NAMES utf8mb4 */;
    
    --
    -- Database: `emp_demo_database`
    --
    
    -- --------------------------------------------------------
    
    --
    -- Table structure for table `employees`
    --
    
    CREATE TABLE `employees` (
      `id` int(11) NOT NULL,
      `name` varchar(40) DEFAULT NULL,
      `address` varchar(50) DEFAULT NULL,
      `salary` int(10) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    --
    -- Dumping data for table `employees`
    --
    
    INSERT INTO `employees` (`id`, `name`, `address`, `salary`) VALUES
    (1, 'JOSEPH SMITH', '8500 NORMANDALE LAKE BLVD, BLOOMINGTON', 30000),
    (2, 'TIM FREDRICKSON', '843 HOLY OAK DRIVE, EDMONTON, CANADA', 60000);
    
    --
    -- Indexes for dumped tables
    --
    
    --
    -- Indexes for table `employees`
    --
    ALTER TABLE `employees`
      ADD PRIMARY KEY (`id`);
    
    --
    -- AUTO_INCREMENT for dumped tables
    --
    
    --
    -- AUTO_INCREMENT for table `employees`
    --
    ALTER TABLE `employees`
      MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
    COMMIT;
    
    /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
    /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
    /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: www-conf
data:
  www.conf: | 
    clear_env = no