---
apiVersion: v1
kind: Service
metadata:
  name: {{include "helm1.fullname" .}}-phpservice
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{.Values.phpService.type}}
  selector:
    app: {{include "helm1.fullname" .}}-php
  ports:
    - protocol: TCP
      port: {{.Values.phpService.externalPort}}
      targetPort: {{.Values.phpService.internalPort}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{include "helm1.fullname" .}}-phpmysql
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    app: {{include "helm1.fullname" .}}-mysql
  ports:
    - port: {{.Values.mysqlService.targetPort}}
      targetPort: {{.Values.mysqlService.targetPort}}
